In [110]:
import torch
import torch.nn as nn
from torch.nn import functional as fn

In [61]:
class Config():
    def __init__(self, vocab_size, context_size, batch_size):
        self.n_layer = 1
        self.n_head = 4
        self.embed_size = 8
        self.vocab_size = vocab_size
        self.context_size = context_size
        self.batch_size = batch_size


In [ ]:
class GPT(nn.Module):
    
    def __init__(self, config):
        super().__init__()
        self.config = config
        

In [229]:
import utils.preprocess as pp
reload(pp)

<module 'utils.preprocess' from '/home/davids/projects/intro-transformer/utils/preprocess.py'>

In [198]:
sites = pp.load_data('data/restriction-sites.txt')

In [199]:
vocab = pp.get_vocab(sites)

In [200]:
config = Config(
    vocab_size = len(vocab),
    context_size = max_len,
    batch_size = 4
)

In [201]:
lns = [len(site) for site in sites]

In [202]:
n_samples = len(site)

In [203]:
init_code = vocab.index('^')
term_code = vocab.index('$')

In [204]:
print(sites[0])
print(encode(sites[0], vocab))
print(decode([30, 15, 15, 4, 17, 19, 26, 26, 0], vocab))

^AA/CGTT$
tensor([30, 15, 15,  4, 17, 19, 26, 26,  0])
^AA/CGTT$


In [205]:
sites_encoded = [pp.encode(site, vocab) for site in sites]

In [206]:
sites_encoded[0]

tensor([30, 15, 15,  4, 17, 19, 26, 26,  0])

[(tensor([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30]),
  tensor(15)),
 (tensor([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15]),
  tensor(15)),
 (tensor([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 15]),
  tensor(4)),
 (tensor([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 15,  4]),
  tensor(17)),
 (tensor([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 15,  4, 17]),
  tensor(19)),
 (tensor([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 15,  4, 17, 19]),
  tensor(26)),
 (tensor([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 15,  4, 17, 19, 26]),
  tensor(26)),
 (tensor([30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 15,  4, 17, 19, 26, 26]),
  tensor(0))]

In [234]:
data = pp.get_batch(sites_encoded, config.batch_size, config.context_size, init_code)

(tensor([[30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
         [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15],
         [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 15],
         [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 15, 26],
         [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 15, 26,  4],
         [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 15, 26,  4, 15],
         [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 15, 26,  4, 15, 26],
         [30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 15, 26,  4, 15, 26, 26],
         [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
         [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15],
         [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 15],
         [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 15, 26],
         [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 15, 26,  4],
         [30, 30, 30, 30,